### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by rhuppert** [RailsApps/rails-signup-download#3]
I hope I am not jumping the gun as I had Ruby 2.2.2 and Rails 4.2.1, plus rbenv already installed, but otherwise I am following the instructions.  When I run the apps composer, I get errors.  I was quite a ways into the stripe-membership tutorial, when I experienced problems and decided to start over.  This time I watched the complete composer installation process and saw the errors.

```
        init  applying migrations and seeding the database
         run    bundle exec rake db:migrate from "."
rake aborted!
Psych::SyntaxError: (<unknown>): did not find URI escaped octet while parsing a tag at line 18 column 28
/home/ron/projects/rails-stripe-membership-saas/config/environments/development.rb:33:in `block in <top (required)>'
/home/ron/projects/rails-stripe-membership-saas/config/environments/development.rb:1:in `<top (required)>'
/home/ron/projects/rails-stripe-membership-saas/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
         run    bundle exec rake db:seed from "."
rake aborted!
Psych::SyntaxError: (<unknown>): did not find URI escaped octet while parsing a tag at line 18 column 28
/home/ron/projects/rails-stripe-membership-saas/config/environments/development.rb:33:in `block in <top (required)>'
/home/ron/projects/rails-stripe-membership-saas/config/environments/development.rb:1:in `<top (required)>'
/home/ron/projects/rails-stripe-membership-saas/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:abort_if_pending_migrations => environment
(See full trace by running task with --trace)
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: set up database" from "."
    generate    layout:devise bootstrap3 -f
/home/ron/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse': (<unknown>): did not find URI escaped octet while parsing a tag at line 18 column 28 (Psych::SyntaxError)
```

**Comment by rhuppert** [comment]
There seems to be an issue with the parsing of 
```
    domain: Rails.application.secrets.domain_name,
```
in development.rb

I tried this again with a clean setup.  I am using Ubuntu 14.04 with node.js.  The composer had the following errors:
```
       apply  https://raw.github.com/RailsApps/rails-composer/master/composer.rb
https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2119: warning: regular expression has ']' without escape: /<%= ENV\["PRODUCT_TITLE"] %>/
https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2120: warning: regular expression has ']' without escape: /<%= ENV\["PRODUCT_PRICE"] %>/
...
        init  applying migrations and seeding the database
         run    bundle exec rake db:migrate from "."
rake aborted!
Psych::SyntaxError: (<unknown>): did not find URI escaped octet while parsing a tag at line 18 column 28
/home/ron/projects/rails-stripe-membership-saas/config/environments/development.rb:33:in `block in <top (required)>'
...
         run    bundle exec rake db:seed from "."
rake aborted!
Psych::SyntaxError: (<unknown>): did not find URI escaped octet while parsing a tag at line 18 column 28
/home/ron/projects/rails-stripe-membership-saas/config/environments/development.rb:33:in `block in <top (required)>'
...
    generate    layout:devise bootstrap3 -f
/home/ron/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse': (<unknown>): did not find URI escaped octet while parsing a tag at line 18 column 28 (Psych::SyntaxError)
  from /home/ron/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
  from /home/ron/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:318:in `parse'
  from /home/ron/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:245:in `load'
  from /home/ron/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:391:in `secrets'
  from /home/ron/projects/rails-stripe-membership-saas/config/environments/development.rb:33:in `block in <top (required)>'
...
    generate    layout:navigation -f
/home/ron/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse': (<unknown>): did not find URI escaped octet while parsing a tag at line 18 column 28 (Psych::SyntaxError)
  from /home/ron/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
  from /home/ron/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:318:in `parse'
  from /home/ron/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:245:in `load'
  from /home/ron/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:391:in `secrets'
  from /home/ron/projects/rails-stripe-membership-saas/config/environments/development.rb:33:in `block in <top (required)>'
```
Hope that helps.

**Comment by rhuppert** [comment]
Asked the question on S.O.

**Comment by rhuppert** [comment]
The issue had to do with pre-existing environment variables in .bashrc, although I am not clear what the problem was.  I commented out those lines, which enabled composer to install the app properly.  The format of those variables seem proper and had not caused issues in the past.  It became clear there was a problem parsing Rails.appplication.secrets.  I suspect a conflict when you have existing ENV and are using secrets.yml in development.
